import type { Metadata } from "next";
import * as GoogleFonts from "./styles/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${GoogleFonts.poiretOne.variable} ${GoogleFonts.notojp.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
