'use client';

export default function Home() {
  return (
    <>
      <section>
        <h2>Cafein</h2>
        <ul>
          <li>駅カフェ路線図掲載サイト</li>
          <li>サイト：https://take4b-cafein.netlify.app/</li>
          <li>コード：https://github.com/take4bcreators/cafe-train-prj</li>
        </ul>
      </section>
      <section>
        <h2>TEMPORALLY</h2>
        <ul>
          <li>すごろく拡張ツール (WEBツール)</li>
          <li>サイト：https://extensionlab-temporally.netlify.app/</li>
          <li>
            コード：
            <ul>
              <li>
                【フロント】https://github.com/take4bcreators/expand-sugoroku-project-front
              </li>
              <li>
                【バッチ】https://github.com/take4bcreators/expand-sugoroku-project-batch
              </li>
              <li>
                【サーバ構築】https://github.com/take4bcreators/expand-sugoroku-project-server
              </li>
            </ul>
          </li>
        </ul>
      </section>
      <section>
        <h2>フリフリフリック</h2>
        <ul>
          <li>WEBゲーム</li>
          <li>
            サイト：https://extensionlab-temporally.netlify.app/minigame/furiwake/
          </li>
          <li>
            コード：https://github.com/take4bcreators/expand-sugoroku-minigame-furiwake
          </li>
        </ul>
      </section>
      <section>
        <h2>extensionLAB</h2>
        <ul>
          <li>WEBツール紹介サイト</li>
          <li>サイト：https://extensionlab.netlify.app/</li>
        </ul>
      </section>
      <section>
        <h2>シンケイスイジャックポッド</h2>
        <ul>
          <li>トランプ拡張ツール</li>
          <li>サイト：https://extensionlab.netlify.app/app/app01/</li>
        </ul>
      </section>
      <section>
        <h2>大富豪スイッチ</h2>
        <ul>
          <li>トランプ拡張ツール</li>
          <li>サイト：https://extensionlab.netlify.app/app/app02/</li>
        </ul>
      </section>
      <section>
        <h2>STURTER</h2>
        <ul>
          <li>自作iPhoneアプリ紹介サイト</li>
          <li>サイト：https://exit1991.github.io/sturter/index.html</li>
          <li>コード：https://github.com/exit1991/sturter</li>
        </ul>
      </section>
      <section>
        <h2>POINTS</h2>
        <ul>
          <li>WEBツール</li>
          <li>サイト：https://dexit-output-points.netlify.app/</li>
          <li>コード：https://github.com/exit1991/simple-web-score</li>
        </ul>
      </section>
      <section>
        <h2>WOLFFICE</h2>
        <ul>
          <li>人狼パーティツール</li>
          <li>
            コード：
            <ul>
              <li>
                【フロントエンド】https://github.com/take4bcreators/jinro-party-frontend
              </li>
              <li>
                【バックエンド】https://github.com/take4bcreators/jinro-party-backend
              </li>
              <li>
                【構築】https://github.com/take4bcreators/jinro-party-server
              </li>
            </ul>
          </li>
        </ul>
      </section>
    </>
  );
}
